new article about best pratices
Slashgear/slashgear.github.io pull request #29
Opened 2021-08-05 10:19 UTC by Slashgear

2021-08-23 07:44 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Pour faire simple, on évite dans la mesure du possible de dire "On devrait faire les choses comme cela", et on préfère "on va coder un truc qui le nous vérifie à notre place".
```suggestion
Pour faire simple, on évite dans la mesure du possible de dire "On devrait faire les choses comme cela", et on préfère "on va coder un truc qui nous le vérifie à notre place".
```

2021-08-23 07:44 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- "Ok c'est intéressant, mais comment peut-on s'assurer qu'on le fasse comme cela automatiquement avec notre CI (Intégration continue) ?"
```suggestion
- "Ok c'est intéressant, mais comment peut-on s'assurer qu'on fasse comme cela automatiquement avec notre CI (Intégration continue) ?"
```

2021-08-23 07:45 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Les reviews n'en sont que plus simple car vous n'avez plus à vous soucier de l'ensemble des règles qui sont déjà automatisées.
```suggestion
Les reviews n'en sont que plus simples car vous n'avez plus à vous soucier de l'ensemble des règles qui sont déjà automatisées.
```

2021-08-23 07:46 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +De nombreuses règles Eslint le propose, et cela est vraiment un critère de sélection très important dans nos choix de nouvelles conventions.
```suggestion
De nombreuses règles Eslint le proposent, et cela est vraiment un critère de sélection très important dans nos choix de nouvelles conventions.
```

2021-08-23 07:46 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Un règle très stricte qui vous obligera à modifier votre code manuellement avant chaque push est pénible à la longue et énervera vos équipes.
```suggestion
Une règle très stricte qui vous obligera à modifier votre code manuellement avant chaque push est pénible à la longue et énervera vos équipes.
```

2021-08-23 07:47 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Alors qu'une règle (même très stricte) qui peut s'autofixer automatiquement au moment du commit ne sera pas perçu comme gênante.
```suggestion
Alors qu'une règle (même très stricte) qui peut s'autofixer automatiquement au moment du commit ne sera pas perçue comme gênante.
```

2021-08-23 07:51 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Pour cela, on essaye d'éviter des débats sempiternel et on se plie à la tendance et aux règles de la communauté.
```suggestion
Pour cela, on essaie d'éviter les débats sempiternels et on se plie à la tendance et aux règles de la communauté.
```

2021-08-23 07:52 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +  On utilise un outil maison mais on peut vous recommander l'outils [BuildTracker](https://buildtracker.dev/).
```suggestion
  On utilise un outil maison mais on peut vous recommander l'outil [BuildTracker](https://buildtracker.dev/).
```

2021-08-23 07:53 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- La couverture de tests n'est pas un indicateur pour l'équipe, toutes les lignes n'ont pas la même nécessité pour nous d'être testée.
```suggestion
- La couverture de tests n'est pas un indicateur pour l'équipe, toutes les lignes n'ont pas la même nécessité pour nous d'être testées.
```

2021-08-23 07:53 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- Les logs de nos tests E2E sont récupérés est parsés afin d'éviter l'introduction d'erreur ou de React warning (Le script de parsing est cependant compliqué à maintenir)
```suggestion
- Les logs de nos tests E2E sont récupérés et parsés afin d'éviter l'introduction d'erreur ou de React warning (Le script de parsing est cependant compliqué à maintenir)
```

2021-08-23 07:54 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +  Nous surveillons que nos tests ne dépendent pas d'une API non moquée qui pourrait ralentir leur execution.
```suggestion
  Nous surveillons que nos tests ne dépendent pas d'une API non moquée qui pourrait ralentir leur exécution.
```

2021-08-23 07:55 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- Le projet est un monorepo sur lequel nous essayons de maintenir les mêmes version de dépendances pour chaque package.
```suggestion
- Le projet est un monorepo sur lequel nous essayons de maintenir les mêmes versions de dépendances pour chaque package.
```

2021-08-23 07:55 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- On vérifie que le notre fichier `yarn.lock` n'a pas été modifié par inadvertance ou bien qu'il a été bien mis à jour par rapport aux modifications du `package.json`.
```suggestion
- On vérifie que notre fichier `yarn.lock` n'a pas été modifié par inadvertance ou bien qu'il a été bien mis à jour par rapport aux modifications du `package.json`.
```

2021-08-23 07:58 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- Grâce notre libraire [_superagent-mock_](https://www.npmjs.com/package/superagent-mock), nous pouvons _fixturer_ (bouchonner, mocker) toutes les API dont on dépend et ainsi même vérifier les cas d'
```suggestion
- Grâce notre librairie [_superagent-mock_](https://www.npmjs.com/package/superagent-mock), nous pouvons _fixturer_ (bouchonner, mocker) toutes les API dont on dépend et ainsi même vérifier les cas d'erreurs.
```

2021-08-23 08:00 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- Les nouvelles recrues de nos équipes ont souvent jamais réalisés ce genre de tests, il y a donc une phase ~~de galère~~ d'apprentissage..
```suggestion
- Les nouvelles recrues de nos équipes n'ont souvent jamais réalisé ce genre de tests, il y a donc une phase ~~de galère~~ d'apprentissage..
```

2021-08-23 08:00 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Pour compléter nos tests fonctionnels nous avons également une stack de tests écris avec [Jest].
```suggestion
Pour compléter nos tests fonctionnels nous avons également une stack de tests écrits avec [Jest].
```

2021-08-23 08:03 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Par principe, nous souhaitons faire en sorte que chaque nouvelle fonctionnalitée de l'application ne base pas son activation sur le simple fait d'être dans la codebase.
```suggestion
Par principe, nous souhaitons faire en sorte que chaque nouvelle fonctionnalité de l'application ne base pas son activation sur le simple fait d'être dans la codebase.
```

2021-08-23 08:03 UTC, kennydee requested changes
1ère salve, je finirais le reste plus tard

2021-08-23 08:03 UTC, kennydee commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +  Nous surveillons que nos tests ne dépendent pas d'une API non moquée qui pourrait ralentir leur execution.
```suggestion
  Nous surveillons que nos tests ne dépendent pas d'une API non mockée qui pourrait ralentir leur execution.
```

2021-08-23 08:03 UTC, kennydee commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- Durant les tests E2E nous vérifions qu'aucune requête d'image n'a généré une 404.
```suggestion
- Durant les tests E2E nous vérifions qu'aucune requête d'image n'a générée une 404.
```

2021-08-23 08:04 UTC, hpierre74 commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Dans notre config il y a une _map_ clé/valeur qui liste toutes les fonctionnalités de l'application associée à leur status d'activation.
```suggestion
Dans notre config il y a une _map_ clé/valeur qui liste toutes les fonctionnalités de l'application associées à leur statut d'activation.
```

2021-08-23 08:16 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +J'ai par le passé travaillé sur des projets bien moins vieux mais sur lesquelles le développement de nouvelles fonctionnalités était bien plus pénible.
```suggestion
J'ai par le passé travaillé sur des projets bien moins vieux mais sur lesquels le développement de nouvelles fonctionnalités était bien plus pénible.
```

2021-08-23 08:21 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +  Nous surveillons que nos tests ne dépendent pas d'une API non moquée qui pourrait ralentir leur exécution.
moquée ou mockée ? 🤔

2021-08-23 08:21 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- Durant les tests E2E nous vérifions qu'aucune requête d'image n'a générée une 404.
```suggestion
- Durant les tests E2E nous vérifions qu'aucune requête d'image n'a généré une 404.
```

2021-08-23 08:22 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- On vérifie quelques règles sur le CSS avec [Stylelint](https://stylelint.io/) et [bemlinter](https://github.com/M6Web/bemlinter) (on utilise plus BEM aujourd'hui mais il reste encore un peu de styl
```suggestion
- On vérifie quelques règles sur le CSS avec [Stylelint](https://stylelint.io/) et [bemlinter](https://github.com/M6Web/bemlinter) (on n'utilise plus BEM aujourd'hui mais il reste encore un peu de style géré en SCSS qu'on migre petit à petit en StyledComponent)
```

2021-08-23 08:23 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +## Tester, tester et tester
le dernier tester est-il différent des deux premiers ? 
```suggestion
## Tester, tester, tester
```

2021-08-23 08:26 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- WebdriverIO nous permet également de lancer de manière journalière ces mêmes tests sur des vrais device en passant par le service [Browserstack](https://www.browserstack.com/).
```suggestion
- WebdriverIO nous permet également de lancer de manière journalière ces mêmes tests sur des vrais devices en passant par le service [Browserstack](https://www.browserstack.com/).
```

2021-08-23 08:32 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Une dépendance, c'est souvent très facile à ajouter mais elle pet devenir un vrai casse-tête à enlever.
```suggestion
Une dépendance, c'est souvent très facile à ajouter mais elle peut devenir un vrai casse-tête à enlever.
```

2021-08-23 08:32 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Les libraires de composants graphiques (expemple React bootstrap, Material Design) sont un bel exemple de dépendance que nous tenons à ne pas introduire.
```suggestion
Les libraires de composants graphiques (exemple React bootstrap, Material Design) sont un bel exemple de dépendance que nous tenons à ne pas introduire.
```

2021-08-23 08:32 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Cela ne nous satisfait pas car certaines dépendances peuvent se retrouvées oubliées.
```suggestion
Cela ne nous satisfait pas car certaines dépendances peuvent se retrouver oubliées.
```

2021-08-23 08:56 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +  Nous surveillons que nos tests ne dépendent pas d'une API non moquée qui pourrait ralentir leur exécution.
```suggestion
  Nous surveillons que nos tests ne dépendent pas d'une API non mockée qui pourrait ralentir leur exécution.
```

2021-08-23 10:00 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +date: 2021-08-05
```suggestion
date: 2021-08-25
```

2021-08-23 10:01 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +À Bedrock Streaming de nombreuses équipes développent et maintiennent des applications _frontend_ pour nos clients et utilisateurs.
"À" ou "chez" ? 
Je pense à "je vais au coiffeur" vs "je vais chez le coiffeur"

2021-08-23 10:01 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Certaines de ces applications ne sont pas toute jeune.
"de ces applications" n'est pas nécessaire

2021-08-23 10:02 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +En effet, si on prend l'exemple de l'application sur laquelle je travaille principalement, il s'agit d'un site web dont les développements ont commencé en 2014.
"En effet, l'application sur laquelle je travaille principalement est un site web dont les développements ont commencé en 2014" ?

2021-08-23 10:03 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +J'ai d'ailleurs déjà évoqué celle-ci dans différents articles de [ce blog](https://slashgear.github.io/).
"Je l'ai d'ailleurs déjà évoquée dans…"

2021-08-23 10:04 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +J'ai par le passé travaillé sur des projets bien moins vieux mais sur lesquels le développement de nouvelles fonctionnalités était bien plus pénible.
"j'ai par le passé travaillé" c'est un peu lourd.
"j'ai travaillé", ça indique déjà que c'est "par le passé", puisque c'est conjugué au passé ;-)

2021-08-23 10:05 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +![nombre de version de l'application 1445](./releases.png)
versions au pluriel ?

2021-08-23 10:06 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +De plus, dans le contexte de ce projet spécifique, en presque 10 ans, nous avons connu une centaine de contributeurs.
"ce projet spécifique" -> le "spécifique" me semble superflu, puisque c'est déjà "ce projet"

2021-08-23 10:06 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Certains développeurs ne sont restés que quelques mois/années.
Le mot "développeurs" pourrait être supprimé, "certains ne sont restés" fait alors référence aux contributeurs de la phrase précédente.

2021-08-23 10:07 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Comment fait-on pour garder au maximum la connaissance sur "Comment on fait les choses et comment ça marche ?" dans un contexte humain si mouvant ?
"comment fait-on pour garder au maximum…" pourrait être allégé en "comment garder au maximum…"

2021-08-23 10:09 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +C'est ce que je vous propose de vous présenter dans cet article.
"C'est ce que je vais vous présenter". Pas besoin de proposer, fais le.

2021-08-23 10:09 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +C'est ce que je vous propose de vous présenter dans cet article.
au pire, les gens pas content s'en iront, que tu leur proposes ou pas ^^

2021-08-23 10:10 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Avec [Florent Dubost](https://twitter.com/fooragnak), on s'est souvent dit qu'il serait intéressant de le publier.
"le publier" -> "la publier" ?
pour "la liste des bonnes pratiques"

2021-08-23 10:10 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +On espère que cela vous sera utile.
"On" c'est un peu impersonnel. "Nous" ?

2021-08-23 10:13 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +On trouve qu'automatiser la vérification de chacune des règles qu'on s'impose (sur notre codebase ou nos process) est bien plus pérenne.
"on trouve qu'automatiser la vérification… est bien plus pérenne"
Tu peux l'affirmer : "automatiser la vérification… est bien plus pérenne"

Ton texte a plus de poids, de force, si tu affirmes, plutot que si "on trouve"

2021-08-23 10:15 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- "Ok c'est intéressant, mais comment peut-on s'assurer qu'on fasse comme cela automatiquement avec notre CI (Intégration continue) ?"
"mais" dans la seconde phrase identifie une "objection".
Tu peux être plus "positif", plus "constructif" avec un "et" : "c'est intéressant et…"

2021-08-23 10:17 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Il n'y a rien de mieux que l'intégration continue d'un projet pour ne rien louper sur chacune des _Pull Request_ qu'on est amené à proposer.
"il n'y a rien de mieux" "pour ne rien louper" > ça fait deux formulations négatives qui s'enchainent, ça demande de réfléchir pour comprendre.
"L'intégration continue d'un projet est la solution parfaite pour ne rien louper sur chacune des PR que nous proposons" (et en plus, enlevons le "qu'on est amené à")

2021-08-23 10:22 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Étant donné qu'un projet n'est pas quelque chose de figé, ces règles vont évoluer avec le temps.
"Un projet n'est pas figé. Ces règles évoluent donc avec le temps."

2021-08-23 10:31 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- On utilise un [nommage de commit bien spécifique](https://www.conventionalcommits.org/en/v1.0.0/) pour générer nos changelog.
J'aimais bien le "nous" à la ligne précédente \o/
Et là on revient à "on" :-(

2021-08-23 10:35 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Ce navigateur va réaliser des actions qui se rapprochent le plus de celles que nos vrais utilisateurs peuvent réaliser tout en vérifiant comment le site réagit.
"Ce navigateur va réaliser" -> "Il réalise"

"nos vrais utilisateur peuvent réaliser" -> "nos utilisateurs réalisent" ?

2021-08-23 10:35 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Ce navigateur va réaliser des actions qui se rapprochent le plus de celles que nos vrais utilisateurs peuvent réaliser tout en vérifiant comment le site réagit.
et encore, ça fait deux fois "réalise", faudrait trouver un synonyme ^^

2021-08-23 10:37 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Voilà un petit schéma qui explique un peu comment cette stack fonctionne:
"petit" et "un peu" sont inutiles et dévalorisants

2021-08-23 10:45 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- nous aider à développer nos modules JS avec des pratiques TDD.
je crois avoir lu plus haut que les tests e2e servaient aussi pour faire du TDD ?

2021-08-23 10:46 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- tester des cas limites qui sont très/trop compliqués à tester avec nos tests E2E.
"qui sont" peut être enlevé

2021-08-23 10:46 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- faciliter le refactoring de notre application en nous montrant les impactes techniques de nos modifications.
"impactes" -> "impacts"

2021-08-23 11:10 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- faciliter le refactoring de notre application en nous montrant les impactes techniques de nos modifications.
```suggestion
- faciliter le refactoring de notre application en nous montrant les impacts techniques de nos modifications.
```

2021-08-23 11:11 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- tester des cas limites qui sont très/trop compliqués à tester avec nos tests E2E.
```suggestion
- tester des cas limites très/trop compliqués à tester avec nos tests E2E.
```

2021-08-23 11:11 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- nous aider à développer nos modules JS avec des pratiques TDD.
Oui, mais pas directement au niveau des modules JS

2021-08-23 11:11 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Voilà un petit schéma qui explique un peu comment cette stack fonctionne:
```suggestion
Voilà un schéma qui explique comment cette stack fonctionne:
```

2021-08-23 11:12 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Ce navigateur va réaliser des actions qui se rapprochent le plus de celles que nos vrais utilisateurs peuvent réaliser tout en vérifiant comment le site réagit.
```suggestion
Ce navigateur va réaliser des actions qui se rapprochent le plus de celles que nos vrais utilisateurs peuvent faire tout en vérifiant comment le site réagit.
```

2021-08-23 11:12 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- On utilise un [nommage de commit bien spécifique](https://www.conventionalcommits.org/en/v1.0.0/) pour générer nos changelog.
```suggestion
- Nous utilisons un [nommage de commit bien spécifique](https://www.conventionalcommits.org/en/v1.0.0/) pour générer nos changelog.
```

2021-08-23 11:13 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Étant donné qu'un projet n'est pas quelque chose de figé, ces règles vont évoluer avec le temps.
```suggestion
Un projet n'est pas figé. Ces règles évoluent donc avec le temps.
```

2021-08-23 11:14 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Il n'y a rien de mieux que l'intégration continue d'un projet pour ne rien louper sur chacune des _Pull Request_ qu'on est amené à proposer.
```suggestion
L'intégration continue d'un projet est la solution parfaite pour ne rien louper sur chacune des _Pull Request_ que nous proposons.
```

2021-08-23 11:15 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- "Ok c'est intéressant, mais comment peut-on s'assurer qu'on fasse comme cela automatiquement avec notre CI (Intégration continue) ?"
Le mais a ici pour sens l'objection.
Si une règle nous parait une bonne idée mais qu'elle ne s'automatise pas, on préfère souvent ne pas l'appliquer.

2021-08-23 11:16 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +On trouve qu'automatiser la vérification de chacune des règles qu'on s'impose (sur notre codebase ou nos process) est bien plus pérenne.
```suggestion
Automatiser la vérification de chacune des règles qu'on s'impose (sur notre codebase ou nos process) est bien plus pérenne.
```

2021-08-23 11:16 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +On espère que cela vous sera utile.
```suggestion
Nous espèrons que cela vous sera utile.
```

2021-08-23 11:16 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Avec [Florent Dubost](https://twitter.com/fooragnak), on s'est souvent dit qu'il serait intéressant de le publier.
```suggestion
Avec [Florent Dubost](https://twitter.com/fooragnak), on s'est souvent dit qu'il serait intéressant de la publier.
```

2021-08-23 11:17 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +C'est ce que je vous propose de vous présenter dans cet article.
```suggestion
C'est ce que je vous propose de vous présenter.
```

2021-08-23 11:17 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Comment fait-on pour garder au maximum la connaissance sur "Comment on fait les choses et comment ça marche ?" dans un contexte humain si mouvant ?
```suggestion
Comment garder au maximum la connaissance sur "Comment on fait les choses et comment ça marche ?" dans un contexte humain si mouvant ?
```

2021-08-23 11:17 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Certains développeurs ne sont restés que quelques mois/années.
```suggestion
Certains ne sont restés que quelques mois/années.
```

2021-08-23 11:17 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +De plus, dans le contexte de ce projet spécifique, en presque 10 ans, nous avons connu une centaine de contributeurs.
```suggestion
De plus, dans le contexte de ce projet, en presque 10 ans, nous avons connu une centaine de contributeurs.
```

2021-08-23 11:18 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +![nombre de version de l'application 1445](./releases.png)
```suggestion
![nombre de versions de l'application 1445](./releases.png)
```

2021-08-23 11:18 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +J'ai par le passé travaillé sur des projets bien moins vieux mais sur lesquels le développement de nouvelles fonctionnalités était bien plus pénible.
```suggestion
J'ai travaillé sur des projets bien moins vieux mais sur lesquels le développement de nouvelles fonctionnalités était bien plus pénible.
```

2021-08-23 11:19 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +J'ai d'ailleurs déjà évoqué celle-ci dans différents articles de [ce blog](https://slashgear.github.io/).
```suggestion
Je l'ai d'ailleurs déjà évoquée dans différents articles de [ce blog](https://slashgear.github.io/).
```

2021-08-23 11:19 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +En effet, si on prend l'exemple de l'application sur laquelle je travaille principalement, il s'agit d'un site web dont les développements ont commencé en 2014.
```suggestion
En effet, l'application sur laquelle je travaille principalement est un site web dont les développements ont commencé en 2014.
```

2021-08-23 11:19 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Certaines de ces applications ne sont pas toute jeune.
```suggestion
Certaines ne sont pas toute jeune.
```

2021-08-23 11:20 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +À Bedrock Streaming de nombreuses équipes développent et maintiennent des applications _frontend_ pour nos clients et utilisateurs.
```suggestion
Chez Bedrock Streaming de nombreuses équipes développent et maintiennent des applications _frontend_ pour nos clients et utilisateurs.
```

2021-08-23 12:00 UTC, pmartin commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- "Ok c'est intéressant, mais comment peut-on s'assurer qu'on fasse comme cela automatiquement avec notre CI (Intégration continue) ?"
aaaah, OK :+1: je n'avais pas compris comme ça (que "si ça ne fonctionne pas avec la CI, alors on n'adopte pas l'idée")

2021-08-23 15:59 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +  Il reste cependant **bien meilleur de ne pas conserver un test qui ne vous donnera pas un résultat stable.**
```suggestion
- Il est très facile de coder un test E2E dit _flaky_ (ie: un test qui peut échouer aléatoirement).
  Ils nous font croire que quelque chose est cassé.
  Ils nous prennent parfois du temps à les stabiliser.
  Il reste cependant **bien meilleur de supprimer un test qui ne vous donnera pas un résultat stable.**
```

(perdre du temps, il y a une petite répétition avec le 3ème point)
(Que veux-tu dire dans le dernier point ? Mieux vaut supprimer les tests flaky ?)

2021-08-23 16:02 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +  Pour information, l'infrastructure du site web (à lui seul, juste l'hébergement de nos servers Node + fichiers statiques + CDN) coutent bien moins cher que notre intégration continue.
Ce serait top d'avoir un ordre de grandeur. Qu'en penses tu ? Ou genre de 1 à 5 en terme de cout du site vs CI.

2021-08-23 16:17 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Cela peut changer le rendu d'un composant, changer l'implémentation d'une action Redux ou bien désactivr une route de notre _react-router_.
```suggestion
Cela peut changer le rendu d'un composant, changer l'implémentation d'une action Redux ou bien désactivr une route de notre _react-router_.
```
```suggestion
Cela peut changer le rendu d'un composant, changer l'implémentation d'une action Redux ou bien désactiver une route de notre _react-router_.
```

2021-08-23 16:20 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Grâce au super travail des équipes backend et data, on a pu même étendre l'usage du _feature flipping_ en rendant cette configuration modifiable pour des sous groupes utilsateurs.
```suggestion
Grâce au super travail des équipes backend et data, on a pu même étendre l'usage du _feature flipping_ en rendant cette configuration modifiable pour des sous groupes d'utilsateurs.
``` ?

2021-08-23 16:23 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Afin d'éviter d'oublier de le faire, ou de le faire en retard, nous avons fait en sorte qu'une clé de configuration puisse être activée à partir d'une certaines date.
```suggestion
Afin d'éviter d'oublier de le faire, ou de le faire en retard, nous avons fait en sorte qu'une clé de configuration puisse être activée à partir d'une certaine date.
```
```suggestion
Afin d'éviter d'oublier de le faire, ou de le faire en retard, nous avons fait en sorte qu'une clé de configuration puisse être activée à partir d'une certaines date.
```

2021-08-23 16:26 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Si on observe une variation trop importante, cela peut nous permettre de le détecter.
Je n'ai pas compris la fin de ce paragraphe : de détecter quoi ?

2021-08-23 16:26 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Le monitoring peut également permettre de mieux communiquer avec les clients sur les impactes d'un incident et également d'estimer le nombre d'utilisateurs impactés.
```suggestion
Le monitoring peut également permettre de mieux communiquer avec les clients sur les impacts d'un incident et également d'estimer le nombre d'utilisateurs impactés.
```
```suggestion
Le monitoring peut également permettre de mieux communiquer avec les clients sur les impactes d'un incident et également d'estimer le nombre d'utilisateurs impactés.
```

2021-08-23 16:28 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Elle peuvent faciliter l'intégration dans un premier temps mais celles-ci bloquent souvent la version de votre librairie de composant par la suite.
```suggestion
Elles peuvent faciliter l'intégration dans un premier temps mais celles-ci bloquent souvent la version de votre librairie de composant par la suite.
```

2021-08-23 16:30 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Depuis l'intégration de [signaler des failles de sécurité dans un package NPM](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities), il est possible de savoir si un proj
La phrase donne un français bizarre non ?

2021-08-23 16:30 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Nous avons donc des job journalier sur nos projet qui lancent la commande `yarn audit` afin de nous forcer à appliquer les correctifs.
```suggestion
Nous avons donc des jobs journaliers sur nos projet qui lancent la commande `yarn audit` afin de nous forcer à appliquer les correctifs.
```
```suggestion
Nous avons donc des job journalier sur nos projet qui lancent la commande `yarn audit` afin de nous forcer à appliquer les correctifs.
```

2021-08-23 16:33 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +On considère qu'une partie de l'application qui nous plaît pas mais sur laquelle on n'a pas besoin de travailler (apporter des évolution) ne mérite pas qu'on la refactor.
```suggestion
On considère qu'une partie de l'application qui nous plaît pas mais sur laquelle on n'a pas besoin de travailler (apporter des évolutions) ne mérite pas qu'on la refactor.
```

2021-08-23 16:34 UTC, renaudAmsellem commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Comme dit plus haut, la prochaine évolution d'un bon de code est parfois sa désactivation.
un bon de code ?

2021-08-23 16:35 UTC, renaudAmsellem approved these changes
👍

2021-08-23 17:21 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- On vérifie que notre fichier `yarn.lock` n'a pas été modifié par inadvertance ou bien qu'il a été bien mis à jour par rapport aux modifications du `package.json`.
ou bien qu'il a été bien > un de nous est de trop, dit le bien

2021-08-23 17:24 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- vie sa vie de fonctionnalité (avec parfois des bugs et des correctifs)
```suggestion
- vis sa vie de fonctionnalité (avec parfois des bugs et des correctifs)
```

2021-08-23 17:25 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +C'est évolution graphique n'était qu'une clé de featureFlipping.
```suggestion
Cette évolution graphique n'était qu'une clé de featureFlipping.
```

2021-08-23 17:30 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +On part du principe qu'aucune fonctionalité ne marche tant qu'elle n'est pas monitorée.
```suggestion
On part du principe qu'aucune 
fonctionnalité ne marche tant qu'elle n'est pas monitorée.
```

2021-08-23 17:30 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Aujourd'hui le monitoring à Bedrock coté Frontend se matérialise par différents outils et différentes stack.
stacks

2021-08-23 17:31 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Avec la multiplication de nos client, bien monitorer nos plateformes n'est plus suffisant.
```suggestion
Avec la multiplication de nos clients, bien monitorer nos plateformes n'est plus suffisant.
```

2021-08-23 17:33 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Une fois qu'on a confiance aux mesures, on peut facilement mettre en place des alertes qui vont nous prévenir en cas de valeur incohérente.
ca sonne bizarrement `on a confiance aux mesures`

2021-08-23 17:36 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +Depuis l'intégration de [signaler des failles de sécurité dans un package NPM](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities), il est possible de savoir si un proj
```suggestion
Depuis l'ajout du [signalement de failles de sécurité dans un package NPM](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities), il est possible de savoir si un projet intègre une dépendance qui contient une faille de sécurité connue par une simple commande.
```

2021-08-23 17:37 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +On va envisager de les inclure prochainement.
utile ?

2021-08-23 17:38 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +On considère qu'une partie de l'application qui nous plaît pas mais sur laquelle on n'a pas besoin de travailler (apporter des évolution) ne mérite pas qu'on la refactor.
```suggestion
On considère qu'une partie de l'application qui ne nous plaît pas mais sur laquelle on n'a pas besoin de travailler (apporter des évolutions) ne mérite pas qu'on la refactorise.
```

2021-08-23 17:43 UTC, fffjacquier commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- On se focus sur nos _pain point_, on refactor ce qu'on a vraiment besoin de faire évoluer.
```suggestion
- On se focalise sur nos _pain points_, on re-factorise ce qu'on a vraiment besoin de faire évoluer.
```

2021-08-24 08:57 UTC, Slashgear commented on src/pages/fr/comment-ne-pas-jeter-son-application-au-bout-de-deux-ans/index.md
> +- On vérifie que notre fichier `yarn.lock` n'a pas été modifié par inadvertance ou bien qu'il a été bien mis à jour par rapport aux modifications du `package.json`.
```suggestion
- On vérifie que notre fichier `yarn.lock` n'a pas été modifié par inadvertance ou bien qu'il a été mis à jour par rapport aux modifications du `package.json`.
```

2021-08-25 06:28 UTC, kennydee approved these changes

2021-08-25 12:25 UTC, merged